### ISSUE TITLE
Release new version of the gem

### ISSUE THREAD

**Issue by davidoh** [heapsource/active_model_otp#108]
Hi team!

Thanks for your efforts maintaining this library. Appreciate it!

Just wondering when you're planning to release a new version of the gem incorporating the latest commit from last week (preventing reuse of OTP codes with ROTP). We'd love to use this feature in our app, so eager to hear when that might be released!

Cheers!

**Comment by guilleiguaran** [comment]
@davidoh hi! I'm tackling one remaining issue this week and then cut a new release.

**Comment by guilleiguaran** [comment]
Version 2.3.2 has been released: https://github.com/heapsource/active_model_otp/releases/tag/v2.3.2
