### ISSUE TITLE
Generate otp_secret_key for some specific users not for all users.

### ISSUE THREAD

**Issue by MohdAnas** [heapsource/active_model_otp#35]
Is there any possibility to generate otp_secret_key only for some specific users not for all users?

**Comment by robertomiranda** [comment]
@MohdAnas sorry for the late response. Unfortunately  Active Model OTP doesn't provide an api that provide such option. But you can override this Instance method on your model Model#otp_regenerate_secret

e.g

```ruby
class User
  def otp_regenerate_secret
    if my_condition
       self.otp_column = ROTP::Base32.random_base32
    end
  end
end
```

**Comment by MohdAnas** [comment]
Can we generate the Key to setup google authenticator instead of scanning the QR code?

**Comment by nashe** [comment]
The result of `ROTP::Base32.random_base32` can be directly used to setup Google Authenticator.

**Comment by MohdAnas** [comment]
I already did that. Thanks for you help.
