### ISSUE TITLE
Undefined method "verify_with_drift" 

### ISSUE THREAD

**Issue by hkairi** [heapsource/active_model_otp#47]
Trying to "authenticate_otp" ==> undefined method `verify_with_drift' for #<ROTP::TOTP:0x00007fb24cee7c48>

**Comment by jeanpauldejong** [comment]
The solution mentioned in the link below resolved it for me https://github.com/heapsource/active_model_otp/issues/46#issuecomment-440442218

You'll have to keep the rotp dependency to the previous version most likely.

```gem 'rotp', '= 3.3.1'```
