### ISSUE TITLE
authenticate_otp now returns timestamp or nil instead of boolean

### ISSUE THREAD

**Issue by asehra** [heapsource/active_model_otp#57]
ROTP changed their implementation of `verify` to return timestamp (eg 1561654770) when the otp is valid and nil otherwise instead of a `true` or `false`. README still says that `authenticate_otp` returns `true` or `false`.

**Comment by Pahicz** [comment]
Is it ok, that I get 0 as return value? I am using counter based OTP.

**Comment by mamaremere** [comment]
@Pahicz , it seems that for counter based OTP, ROTP returns the value of the counter instead of the timestamp. `nil` still means that the token is not verified. Here's the documentation from ROTP: https://github.com/mdp/rotp#counter-based-otps

**Comment by kevinhq** [comment]
We run through this problem too. Getting a timestamp or nil (when it should be false). Any update or workaround for this?

**Comment by mamaremere** [comment]
@kevinhq , this gem, `active_model_otp` respects the response received from `rotp`, the gem that does all the heavy-lifting:

For time-based tokens, `rotp` will return an integer timestamp for success or nil for failure.

For counter-based tokens, `rotp` will return the current count for success or nil for failure.

The docs on this gem should probably be updated, but I don't see much activity from the maintainer.

**Comment by pedrofurtado** [comment]
PR https://github.com/heapsource/active_model_otp/pull/85 merged 🎉
