### ISSUE TITLE
No changelog for 2.0.0 or 2.0.1

### ISSUE THREAD

**Issue by jayqui-omada** [heapsource/active_model_otp#59]
It looks like I can upgrade this gem to 2.0.1 already, but there is no changelog entry describing the breaking changes. Can someone please update this?

**Comment by robertomiranda** [comment]
@jayqui-omada there's was not changes done. I've reflected that on the release https://github.com/heapsource/active_model_otp/releases

**Comment by jayqui-omada** [comment]
I'm confused. Why then was there a minor version upgrade?
