### ISSUE TITLE
undefined method `dark?' when creating QR-Code

### ISSUE THREAD

**Issue by alliedarmour** [heapsource/active_model_otp#61]
When i'm trying to get my QR-Code for the users to work I'm always getting this error message:

**undefined method `dark?' for #<RQRCode::QRCode:0x0000000009b81c18>**

I'm not sure why this happens, I did everything like mentioned and in my controller I require the gem like: require 'rqrcode'

Then I'm trying to generate the QR-Code for 2-Factor-Authentication:
`@qr = RQRCode::QRCode.new(@user.provisioning_uri, :size => 8, :level => :h )
`
And in my view:

```
<table class="qr">
  <% @qr.modules.each_index do |x| %>
      <tr>
        <% @qr.modules.each_index do |y| %>
            <% if @qr.dark?(x,y) %>
                <td class="black">
            <% else %>
                <td class="white">
            <% end %>
        <% end %>
      </tr>
  <% end %>
</table>
```

Any suggestions?

**Comment by davidnghk** [comment]
Got the same error.  No clue

**Comment by catob** [comment]
In case someone else struggles with this: https://github.com/heapsource/active_model_otp/wiki/Generate-QR-code-with-rqrcode-gem#create-the-qr-code
