### ISSUE TITLE
Enable/disable generate opt_secret_key when is an user is created

### ISSUE THREAD

**Issue by nmenag** [heapsource/active_model_otp#71]
Have an option if wish generate the opt_secret_key at the moment of create an user or can is in blank.

**Comment by HichamLaaboudi** [comment]
This would be nice

**Comment by pedrofurtado** [comment]
This feature currently is not a high priority of implementation, but I will be glad to review a PR with some implementation of this, if you can spend some time on it 🤝 🍻 

For a while, I will close the issue, but feel free to reopen when the PR was provided 🥇
