### ISSUE TITLE
Plans to release a new version?

### ISSUE THREAD

**Issue by pedrofurtado** [heapsource/active_model_otp#73]
Is there any Plans to release a new version?

**Comment by pedrofurtado** [comment]
@bartpalmtree @robertomiranda 🤝

**Comment by pedrofurtado** [comment]
Any news?

**Comment by bartpalmtree** [comment]
@pedrofurtado, that'll be a question for @robertomiranda 
I only submitted a PR.

**Comment by pedrofurtado** [comment]
Thanks for feedback @bartpalmtree 🤝

**Comment by robertomiranda** [comment]
@pedrofurtado sorry for the delay, I have just released a brand new version https://github.com/heapsource/active_model_otp/releases/tag/v2.1.0
