### ISSUE TITLE
Error: "NoMethodError (undefined method `before_create' for {}:Hash)" when used with devise on ruby 3.0.0

### ISSUE THREAD

**Issue by Maarius** [heapsource/active_model_otp#75]
I was trying to update my rails app to ruby 3.0.0 and noticed that when I tried to sign up new users using devise I get the following error: 
```
NoMethodError (undefined method `before_create' for {}:Hash):
```
The issue goes away when I comment `has_one_time_password` out in the `User` model so it seems quite likely that it is related to this gem. 
Is this issue known / expected? Otherwise I can gladly post the exact steps to reproduce.

**Comment by thuandoan274** [comment]
I have the same issues like you, also using ruby 3.0.0

>  NoMethodError (undefined method `has_one_time_password' for User:Class)

**Comment by pedropereira** [comment]
Looks like there's a fix being worked on here: https://github.com/heapsource/active_model_otp/pull/77

**Comment by pedrofurtado** [comment]
Glad to see a release with this fix 🎉 🎉

**Comment by pedrofurtado** [comment]
@Maarius I think we can close this issue, because https://github.com/heapsource/active_model_otp/pull/77 was merged 🏁

**Comment by Maarius** [comment]
Awesome! Thanks for the ping @pedrofurtado
