### ISSUE TITLE
Release of a version with Ruby 3 support

### ISSUE THREAD

**Issue by pedrofurtado** [heapsource/active_model_otp#80]
Hey everyone! 👋 

Recently, the support for Ruby 3 was added in gem 🎉 

@robertomiranda and other maintainers, can you please (when you have time) to release a official release with this changes? 👍 

Thanks a lot! 🍻

**Comment by pedrofurtado** [comment]
Any news about it? 🤝 🍻

**Comment by robertomiranda** [comment]
closed by #77
