### ISSUE TITLE
authenticate_otp (counter_based) now returns the corresponding otp_counter or nil instead of a boolean value

### ISSUE THREAD

**Issue by EmCousin** [heapsource/active_model_otp#84]
Hi,

First, thanks for this convenient gem.

This Issue mirrors for HOTP the already existing issue for TOTP here: https://github.com/heapsource/active_model_otp/issues/57

We are well aware that this gem only respects the response received from `rotp` (cf. https://github.com/heapsource/active_model_otp/issues/57#issuecomment-628334701), however this is currently breaking this gem's behavior

This issue is open for tracking purposes. A PR is coming as a proposal to ensure `authenticate_otp` returns a boolean value

**Comment by pedrofurtado** [comment]
PR https://github.com/heapsource/active_model_otp/pull/85 merged 🎉
